sudo: false
language: cpp

compiler:
    - gcc

os:
    - linux
matrix:
    fast_finish: true
env:
    - CMAKE_CONFIGURE_OPTIONS="-DWITH_NEL_TESTS=OFF -DWITH_NEL_SAMPLES=OFF -DWITH_LUA51=ON -DWITH_RYZOM_SERVER=OFF -DWITH_RYZOM_TOOLS=OFF -DWITH_NEL_TOOLS=OFF"
    - CMAKE_CONFIGURE_OPTIONS="-DCPPTEST_LIBRARY_DEBUG:STRING=/usr/lib/libcpptest.so"
      CMAKE_BUILD_OPTIONS="--target nel_unit_test -- -j 2"
      RUN="build/bin/nel_unit_test"

addons:
    apt:
        packages:
            - liblua5.1-dev
            - libluabind-dev
            - libcpptest-dev
            - libogg-dev
            - libvorbis-dev
            - libopenal-dev
            - libgif-dev
            - libfreetype6-dev
            - libxml2-dev

before_script:
    - mkdir build
    - cmake --version
    - cmake -Hcode -Bbuild $CMAKE_CONFIGURE_OPTIONS
    - cat build/CMakeCache.txt

script:
    - cmake --build build $CMAKE_BUILD_OPTIONS
    - $RUN

notifications:
  irc:
    channels:
      - $NOTIFICATION_IRC_CHANNEL
    template:
      - "%{repository}#%{build_number} (%{branch} - %{commit} : %{author}): %{message}"
      - "Description : %{commit_message}"
      - "Change view : %{compare_url}"
      - "Build details : %{build_url}"
