sudo: false
language: cpp

compiler:
    - gcc

os:
    - linux
env:
    - CMAKE_BUILD_OPTIONS="-DWITH_NEL_TESTS:BOOL=off"

addons:
    apt:
        packages:
            - libluabind-dev
            - libcpptest-dev
            - libogg-dev
            - libvorbis-dev
            - libopenal-dev
            - libgif-dev
            - libfreetype6-dev
            - libxml2-dev

before_script:
    - mkdir build
    - cmake --version

script:
    - cmake -Hcode -Bbuild $CMAKE_BUILD_OPTIONS
    - cmake --build build -- -j 2

notifications:
  irc: "chat.freenode.net#ryzomforge"
    template:
      - "%{repository}#%{build_number} (%{branch} - %{commit} : %{author}): %{message}"
      - "Description : %{commit_message}"
      - "Change view : %{compare_url}"
      - "Build details : %{build_url}"
